apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse_raw
    type: clickhouse
    access: proxy
    isDefault: true
    editable: true
    url: http://clickhouse:8123
    database: probablyfresh_raw
